[supervisord]
nodaemon = true
logfile = /dev/null
logfile_maxbytes = 0
pidfile = /run/supervisord.pid
user=root

[unix_http_server]
username = dummy
password = dummy

[program:frankenphp]
command=frankenphp run --config /etc/caddy/Caddyfile --adapter caddyfile
directory=/app
autostart=%(ENV_HUMHUB_DOCKER__AUTOSTART_FRANKENPHP)s
autorestart=true
user=www-data
priority=10
redirect_stderr=false
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:humhub-scheduler]
command=/app/bin/humhub-scheduler.sh
user=www-data
autostart=%(ENV_HUMHUB_DOCKER__AUTOSTART_SCHEDULER)s
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:humhub-worker]
command=/app/bin/humhub-worker.sh
user=www-data
process_name=%(program_name)s_%(process_num)02d
autostart=%(ENV_HUMHUB_DOCKER__AUTOSTART_WORKER)s
autorestart=true
numprocs=%(ENV_HUMHUB_DOCKER__NUMPROCS_WORKER)s
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:humhub-app-log]
command=/app/bin/humhub-app-log.sh
user=www-data
autostart=%(ENV_HUMHUB_DOCKER__ENABLE_APP_LOG_TO_STDOUT)s
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
